site_name: ASO Administración de Sistemas Operativos
site_url: https://joseramonIESMZ.github.io/ASO
docs_dir: docs
use_directory_urls: true

theme:
  name: material
  language: es
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs           # 🚀 OBLIGATORIO: Activa el menú de pestañas superior
    - navigation.tabs.sticky    # Hace que las pestañas superiores se queden fijas
    # ❌ IMPORTANTE: 'toc.integrate' DEBE ESTAR ELIMINADO. Si lo pones, la columna de la derecha se mete dentro de la izquierda y rompe las 3 columnas.
    - content.code.copy
    - search.highlight
    - navigation.sticky
    - navigation.top

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite

nav:
  - 'Inicio': index.md
  - 'Windows Server':
      - 'Fundamentos de Administración de Windows Server': apuntes/windows-server/fundamentos-core.md
      - 'Administración Remota (WinRM)': apuntes/windows-server/administracion-remota.md
      - 'Supervisión y mantenimiento': apuntes/windows-server/supervision-mantenimiento.md
      - 'Programación de tareas': apuntes/windows-server/programacion-tareas.md
      - 'Políticas de Grupo (GPO)': apuntes/windows-server/politicas-gpo.md
      
      