[project]
site_name = "ASO Administración de Sistemas Operativos"
site_url = "https://joseramonIESMZ.github.io/ASO"
docs_dir = "docs"
use_directory_urls = true

extra_css = [
  "stylesheets/extra.css"
]

nav = [
  { "Inicio" = "index.md" }
]

[project.theme]
variant = "classic"
language = "es"
custom_dir = "overrides"

features = [
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "content.code.copy",
  "search.highlight",
  "navigation.sticky",
  "navigation.top"
]