name: Deploy Zensical to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Checkout del repositorio
        uses: actions/checkout@v5

      - name: Configurar entorno de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar Zensical
        run: pip install -r requirements.txt

      - name: Compilar sitio estático
        run: zensical build --clean

      - name: Subir artefacto de Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
